version: 2.1

jobs:
  check-fmt:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: "fmt --check"
          command: "cargo fmt --check"
  test:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: "test"
          command: "cargo test"

workflows:
  all:
    jobs:
      - check-fmt
      - test
